// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH4JBXKhreH-fWxAd1VypNu6NADWJu944',
    appId: '1:158625532022:android:fab4493dd3eea9f9a9b757',
    messagingSenderId: '158625532022',
    projectId: 'task-manager-27b1c',
    storageBucket: 'task-manager-27b1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgVNk91GkczMeJcqgGe1BS3V0fVFLdSaI',
    appId: '1:158625532022:ios:e63b1bf6c5c6dd06a9b757',
    messagingSenderId: '158625532022',
    projectId: 'task-manager-27b1c',
    storageBucket: 'task-manager-27b1c.appspot.com',
    iosClientId: '158625532022-r1so42opj25rgi6nc6mb7s28tc5poe3f.apps.googleusercontent.com',
    iosBundleId: 'com.taskmanagerIOS.app',
  );
}
